version: 0.2

env:
  variables:
    # Provide in CodeBuild project or CodePipeline (do NOT commit real URI)
    ECR_URI: "637423386762.dkr.ecr.us-east-1.amazonaws.com/springboot-app"
phases:
  pre_build:
    commands:
      - echo Logging in to ECR...
      - REGION=us-east-1
      - REGISTRY=611195126552.dkr.ecr.$REGION.amazonaws.com
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $REGISTRY
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo IMAGE_TAG=$IMAGE_TAG
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $ECR_URI:$IMAGE_TAG .
      - docker tag $ECR_URI:$IMAGE_TAG $ECR_URI:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $ECR_URI:$IMAGE_TAG
      - docker push $ECR_URI:latest
      - printf '[{"name":"container","imageUri":"%s"}]' $ECR_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
